Header component with project switch drawer
weareoutofbox/VizDom pull request #11
Opened 2021-10-06 12:40 UTC by braj176

Header component with project switch drawer

2021-10-06 12:51 UTC, PrashantHalaki requested changes
@braj176 Remove the routes for the components. Routes should only be there for pages.

2021-10-06 12:51 UTC, PrashantHalaki commented on vizdom/src/core/routes/routes.js
> +  },
Why do you need a separate route for the header? Integrate it with pages

2021-10-07 05:36 UTC, PrashantHalaki commented on vizdom/src/core/routes/routes.js
> +import HeaderComponent from "../../components/header";
Remove unused import @braj176

2021-10-08 03:45 UTC, braj176 commented on vizdom/src/core/routes/routes.js
> +import HeaderComponent from "../../components/header";
removed unused import

2021-10-08 09:49 UTC, merged